### PR TITLE
169 Finalize plugin interface naming, families, and directory structure

### PR DESCRIPTION
**Pull request by jsolbrig**
# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

Current status, please review the "interfaces", "schema" and "plugins" directories:
* https://github.com/NRLMMD-GEOIPS/geoips/tree/165-use-base-schema-in-all-other-schema/geoips/interfaces
*  https://github.com/NRLMMD-GEOIPS/geoips/tree/165-use-base-schema-in-all-other-schema/geoips/plugins
* https://github.com/NRLMMD-GEOIPS/geoips/tree/165-use-base-schema-in-all-other-schema/geoips/schema

Ensure the following are all true:
* Check to be sure that all interfaces have an associated `plugins` directory and that the names are consistent.
* Check to be sure that all YAML-based interfaces have an associated schema directory and that the names are consistent.
* Check a couple YAML files to be sure that YAML files have appropriately named “interface” and “family” fields where these match the $id field of a YAML schema of the form “$id: <interface>.<family>”

# Related Issues
fixes NRLMMD-GEOIPS/geoips#165
fixes NRLMMD-GEOIPS/geoips#169

# Testing Instructions
Not ready yet

# Summary
This is going to be a major reorg

# Output
Not ready yet.

### CODE REVIEW

**Comment by jsolbrig** [comment]
### Notes from Jeremy

- Currently the error raised when an appropriate family isn't found is `KeyError` from `geoips/schema/plugin_validator.py:105`. This should be something more appropriate to indicate that the appropriate family was not found. To test this, just set `family: standard` for a `product_defaults` plugin.

**Comment by jsolbrig** [comment]
I fixed the above issues.
- To find schema for a particular plugin, we now look for `<interface>.<family>` where `$id` in each schema is set to `<interface>.<family>`. This is true even when `family` is "standard". For example, the `boundaries` interface only has one family, "standard", so `$id` in `boundaries.yaml` is `boundaries.standard`.
- To ensure that `interface` and `family` are correct, I updated the validator to first validate each plugin against the `base` schema, then extract the interface and family fields to find the appropriate schema to validate the rest. It's possible that this will add overhead, but I doubt that it will be significant.

**Comment by mindyls** [comment]
> I fixed the above issues.
> - To find schema for a particular plugin, we now look for `<interface>.<family>` where `$id` in each schema is set to `<interface>.<family>`. This is true even when `family` is "standard". For example, the `boundaries` interface only has one family, "standard", so `$id` in `boundaries.yaml` is `boundaries.standard`.
> - To ensure that `interface` and `family` are correct, I updated the validator to first validate each plugin against the `base` schema, then extract the interface and family fields to find the appropriate schema to validate the rest. It's possible that this will add overhead, but I doubt that it will be significant.

I think we'd talked about making this update earlier too - always validate interface. Family

**Comment by jsolbrig** [comment]
@mindyls Yep, you're right. I just hadn't gotten around to it yet!

**Comment by mindyls** [comment]
Initial commentary in PR:

This PR updates all of the YAML-based interface schema. I'll consider these to be "beta" for now and, likely, subject to some change. Hopefully not much, though.

As part of this PR, which is currently in "draft", we will also update all of the current YAML files to match the current schema.

Things to be completed before taking off "draft" status:

- [ ] Add a product_defaults base schema for windbarbs. **Jeremy**

Ensure that the following plugins all match the current schema (these should all be close):
- [x] `interface_modules/boundaries/`
- [x] `interface_modules/dynamic_sectors/`
- [x] `interface_modules/gridlines/`
- [ ] `interface_modules/product_lists/` **Let Jeremy handle this one**
- [x] `interface_modules/static_sectors/`

Update the following to match the new schema (these will require more work):
- [x] `interface_modules/product_defaults/`
  - [x] `../pmw_37/`
  - [x] `../pmw_89/`
  - [x] `../pmw_150/`
  - [x] `../rain_rate/`
  - [x] `../sfc_winds/`
  - [x] `../tpw/`
  - [x] `../visir/`

**Comment by jsolbrig** [comment]
Closing as not merging. This has been overtaken by other PRs.

**Pull request closed without merging**
