### PR TITLE
fix: Typo fixed from issue #829

### PR DESCRIPTION
**Pull request by Polycarbohydrate**
# Reviewer Checklist

PR author: Please ensure you meet all of the below requirements, and check boxes appropriately.

Reviewers: Please confirm all required testing/documentation has been completed prior to approving.

**Remove lines that are not applicable, explain if you select "NO REQUIRED"**

* [ ] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [ ] NO REQUIRED ***existing tests*** (explain why not required)
* [ ] Required ***unit tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***unit tests*** (explain why not required)
* [ ] Required ***integration tests*** added and pass for new/modified functionality
* [ ] NO REQUIRED ***integration tests*** (explain why not required)
* [ ] Required ***documentation*** added for new/modified functionality
* [ ] NO REQUIRED ***documentation*** (explain why not required)
* [ ] Required ***release notes*** added for new/modified functionality
* [ ] NO REQUIRED ***release notes*** (explain why not required)
* [ ] Required ***updates to other repos*** complete
* [ ] NO REQUIRED ***updates to other repos*** (explain why not required)

https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes https://github.com/NRLMMD-GEOIPS/geoips/issues/829

# Testing Instructions

# Summary

# Output

### CODE REVIEW

**Review by biosafetylvl5 — APPROVED** [review]
Thanks @Polycarbohydrate ! 🙂 

We need one more approval from another maintainer and then we can get this merged in.

**Review by mindyls — APPROVED** [review]
Thanks!!

**Comment by Polycarbohydrate** [comment]
Thanks for the quick and timely reviews! 👍🏼 :)

**Comment by biosafetylvl5** [comment]
Merged! 🎉

**Pull request merged**
