### PR TITLE
Handle xarray in apply_data_range

### PR DESCRIPTION
**Pull request by jsolbrig**
# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
None

# Testing Instructions
- Test this branch along with the `apply_data_range_xarray_fix` branch of template_basic_plugin
- Run full_test.sh
- Test `template_basic_plugin/tests/scripts/amsr2.tc_clean.89-PCT-Fully-Specified.sh`
- Test `template_basic_plugin/tests/scripts/amsr2.global_clean.89-PCT-Using-Product-Defaults.sh`

# Summary
Enhancements
============

Allow apply_data_range to handle xarray
---------------------------------------

* Attempt to convert xarray to numpy array and if that conversion succeeds, convert it
  back to xarray at the end of the function. This is a temporary fix that should be
  addressed more thoroughly in #308.

::

    modified: geoips/data_manipulations/corrections.py

# Output

### CODE REVIEW

**Review by mindyls — APPROVED** [review]
Package: geoips_full
Total run time: 2651 seconds
Number data types run: 47
Number data types failed: 0

**Review by mindyls — APPROVED** [review]
Tests are running now, 0 returns so far (almost through geoips tests).

Looks good to me, thank you for removing the errant docstring update :-)

**Review by christopher-selman — APPROVED** [review]

**Review by cpcamacho — APPROVED** [review]
lgtm

**Review by evrose54 — APPROVED** [review]
Looks good.

**Comment by mindyls** [comment]
I've never seen so many approvals so quickly.

**Pull request merged**
