### PR TITLE
Add xfail for input files error on reader unit-tests

### PR DESCRIPTION
**Pull request by biosafetylvl5**
* [x] Required ***existing tests*** pass (ie full_test.sh, others as appropriate)
* [x] Required ***unit tests*** ~added and~ pass for new/modified functionality
* [x] Required ***integration tests*** ~added and~ pass for new/modified functionality
* [x] NO REQUIRED ***documentation*** (explain why not required)
* [x] Required ***release notes*** added for new/modified functionality
* [x] NO REQUIRED ***updates to other repos***

# Related Issues
fixes NRLMMD-GEOIPS/geoips#794

# Testing Instructions
- Remove AMI test data
- Run `pytest`

# Summary

`main` fails the unit tests. See issue #794. This is purportedly due to missing data, which we don't have the ability to share publicly. This PR changes the failing test to xfail on missing data. HOWEVER this could also xfail on anything else that could raise a ValueError on inconsistent input files. Please review the code to make sure this is an appropriate change.

# Output
`==== 1630 passed, 31 xfailed, 23 warnings in 63.71s (0:01:03) ====`

### CODE REVIEW

**Review by mindyls — APPROVED** [review]
Yay!! Happy to see this .....

**Comment by srikanth-kumar** [comment]
Can we enhance the test to provide a clear reason for skipping it due to the absence of test data, while ensuring that this reason is not applied to other issues?

To achieve this, I think we could make `verify_plugin()` more modular by splitting its functionality into two distinct methods:

-  checking test data presence or test_data_presence() : check if the test data is available
-  parameter validation : validation of dataset parameters

 @biosafetylvl5 please let me know if I'm overlooking something here.

**Comment by biosafetylvl5** [comment]
I agree that adding better error logs to the readers is a good idea. I think it is out of the scope of this PR, as this is a fix to a bug, whereas that is - as I understand things - adding functionality to all of the readers individually. @srikanth-kumar Let me know what you think. I propose opening an issue for adding that.

**Review by jsolbrig — APPROVED** [review]

**Review by srikanth-kumar — APPROVED** [review]

**Comment by srikanth-kumar** [comment]
> @srikanth-kumar Can you clarify what you mean by "parameter validation : validation of dataset parameters"

Along with checking for the presence of test data files, verify_plugin() also calls another method `verify_xarray(self, inxr, test_parameters)` to test whether attributes or parameters exist in the input dataset. 

I stated that this method should be another method.

**Review by jsolbrig — APPROVED** [review]

**Review by mindyls — APPROVED** [review]

**Pull request merged**
