### PR TITLE
Rename FilenameFormattersInterface class to FilenameFormats

### PR DESCRIPTION
**Pull request by lance-wilson**
# Reviewer Checklist
https://github.com/NRLMMD-GEOIPS/.github/blob/main/.github/review-template.md

# Related Issues
fixes NRLMMD-GEOIPS/geoips#92

# Testing Instructions

None

# Summary

### Bug fixes
* filename_formats.py:
  * Renamed FilenameFormattersInterface class to FilenameFormats

# Output

None

### CODE REVIEW

**Review by jsolbrig — COMMENTED** [review]
This looks good to me. @lance-wilson Can you please try running a few of the tests to be sure that the change didn't impact anything? I don't think it should, but it's best to test. I'd recommend testing at least one product that uses the single_source procflow and one that uses the config_based procflow.

**Comment by lance-wilson** [comment]
@jsolbrig I ran the test_full_install.sh and it looks like all of the output was generated fine but the comparisons failed (usually the text files, I think; the image compares seemed to all work).  My fork wasn't setup with conda and my directory structure doesn't quite match the expectation, so I'm not sure if that is messing something up.  Sample images below.
Output image of abi.config_based_output_low_memory.sh:
20200918_195020_AL202020_abi_goes-16_Infrared_110kts_100p00_1p0
Output of abi.static.Visible.imagery_annotated.sh:
20200918 195020 goes-16 abi Visible goes16 41p12 noaa 10p0

**Comment by jsolbrig** [comment]
@lance-wilson I think that all looks correct. Can you take a look at the output comparison images to see what they look like? I would expect all of the clean imagery to pass the comparison tests, but anything annotated may not. You can find the image diffs in `geoips/tests/outputs/<test_name>/diff_test_output_*/diff_test_output_*.png`. What I would expect to see is that the differences (marked in red) are all related to annotations like text and gridlines.

**Comment by lance-wilson** [comment]
I think these look fine but I'm not sure they are rendering correctly.
diff_test_output_exact_20200918 195020 goes-16 abi Visible goes16 41p12 noaa 10p0
diff_test_output_exact_20200918_195020_AL202020_abi_goes-16_Infrared_110kts_100p00_1p0

**Review by mindyls — APPROVED** [review]
I'm convinced!  Good to go from my perspective.

**Comment by jsolbrig** [comment]
Actually, those look exactly as I'd expect them to! Basically, those images appear to be faded because they are showing a diff of your output image against a pre-generated comparison image. The regions where they match are light. The regions where they don't match are marked in bright red. You can see a few pixels here and there, mainly in the text, that are bright red. That is where the images don't quite match.

Unfortunately, until we handle #56, we're going to keep seeing this kind of issue where our output doesn't quite match the comparison images. When they look like what you got, though, things are okay and working as correctly as they can.

**Pull request merged**
